# Get list of all directories in current directory
macro(subdirlist RESULT_LIST CURDIR)
    file(GLOB CHILDREN RELATIVE ${CURDIR} ${CURDIR}/*)
    set(DIRLIST "")
    foreach(CHILD ${CHILDREN})
        if(IS_DIRECTORY ${CURDIR}/${CHILD})
            list(APPEND DIRLIST ${CHILD})
        endif()
    endforeach()
    set(${RESULT_LIST} ${DIRLIST})
endmacro()

# Detect platform and set platform name
macro(detect_platform_name PLATFORM_NAME)
    if(${UNIX})
        if(${APPLE})
            if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
                set(PLATFORM_NAME "osx")
            endif()
        else()
            set(PLATFORM_NAME "linux")
        endif()
    elseif(${WIN32})
        set(PLATFORM_NAME "windows")
    endif()
endmacro()
