name: CMake

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master, dev ]

env:
  BUILD_TYPE: Release
  TESTS_TO_SKIP: system/*|graphics/font|graphics/renderer

jobs:
  build_mac:
    runs-on: [ macos-latest ]
           
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 10

    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -j 10 -E "${{env.TESTS_TO_SKIP}}"
 
  build_windows:
    runs-on: [ windows-latest ]
           
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 10

    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -j 10 -E "${{env.TESTS_TO_SKIP}}"
         
  build_linux:
    runs-on: [ ubuntu-latest ]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Update atp-get
      run: sudo gem install apt-spy2 &&
           sudo apt-spy2 check &&
           sudo apt-spy2 fix --commit &&
           sudo apt-get update
        
    - name: Install X11 and OpenGL
      run: sudo apt-get install -y libx11-dev libgl1-mesa-dev mesa-common-dev
  
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 10

    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -j 10 -E "${{env.TESTS_TO_SKIP}}"
